### ISSUE TITLE
Formatting doc annotations 

### ISSUE THREAD

**Issue by welopino** [ceylon/ceylon.formatter#138] opened 2017-05-10 12:11 UTC
The whitespace before opening "(" causes problems. I use the standard configuration of the formatter of ceylon 1.3.2.:
The result of formatting looks like that:
```
doc ("
     
     fdsfdsfs
     sfds")
by ("
     dsf dsf d
     sf
     sdfa"
)
```

The compiler knows it better than the formatter:

```
source/selftypecheck/run2.ceylon:6: error: multiline string content should align with start of string: string begins at character position 6
doc ("
     ^
1 error
...

```

**Comment by lucaswerkmeister** [comment] 2017-05-10 20:29
I can’t reproduce this – can you please post your original code before formatting?

**Comment by lucaswerkmeister** [comment] 2017-06-01 07:48
To clarify: if you take your result of formatting, and format it again, it will still be broken – but that’s not a bug: it’s only a bug if the formatter takes valid code and breaks it. To fix that, or even know if that’s the case, I need the original, unformatted code.

Also, are you sure you used `ceylon.formatter` and not the IntelliJ IDE’s formatter?

**Comment by lucaswerkmeister** [comment] 2017-08-21 19:56
@welopino if you can’t provide steps to reproduce this, I’ll have to close this issue. `ceylon.formatter` should handle this situation correctly (I remember implementing it – not fun :D ), and I suspect you may have been using IntelliJ’s formatter (which is separate and, as far as I know, less sophisticated).

**Closed** 2017-09-05 19:06 UTC
Labels: bug
